Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,31 +1,76 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/reference/configuration-reference/
 version: 2.1
 
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
 jobs:
-  say-hello:
-    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/guides/execution-managed/executor-intro/ & https://circleci.com/docs/reference/configuration-reference/#executor-job
+  trigger-testrigor-suite:
     docker:
-      # Specify the version you desire here
-      # See: https://circleci.com/developer/images/image/cimg/base
       - image: cimg/base:current
-
-    # Add steps to the job
-    # See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#steps-overview & https://circleci.com/docs/reference/configuration-reference/#steps
     steps:
-      # Checkout the code as the first step.
-      - checkout
       - run:
-          name: "Say hello"
-          command: "echo Hello, World!"
+          name: "Trigger and Wait for testRigor Suite"
+          command: |
+            #!/bin/bash
+            
+            curl -X POST \
+              -H 'Content-type: application/json' \
+              -H "auth-token: ${TESTRIGOR_AUTH_TOKEN}" \
+              --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
+              "https://api.testrigor.com/api/v1/apps/${TESTRIGOR_APP_ID}/retest"
+            
+            sleep 10
+            
+            while true
+            do
+              echo " "
+              echo "==================================="
+              echo " Checking run status"
+              echo "==================================="
+              response=$(curl -i -o - -s -X GET "https://api.testrigor.com/api/v1/apps/${TESTRIGOR_APP_ID}/status" -H "auth-token: ${TESTRIGOR_AUTH_TOKEN}" -H 'Accept: application/json')
+              code=$(echo "$response" | grep HTTP | awk '{print $2}')
+              body=$(echo "$response" | sed -n '/{/,/}/p')
+              
+              echo "Status code: " $code
+              echo "Response: " $body
+              
+              case $code in
+                4*|5*)
+                  # 400 or 500 errors
+                  echo "Error calling API"
+                  exit 1
+                  ;;
+                200)
+                  # 200: successfully finished
+                  echo "Test finished successfully"
+                  exit 0
+                  ;;
+                227|228)
+                  # 227: New - 228: In progress
+                  echo "Test is not finished yet"
+                  ;;
+                229)
+                  # 229: Canceled
+                  echo "Test canceled"
+                  exit 1
+                  ;;
+                230)
+                  # 230: Failed
+                  echo "Test finished but failed"
+                  exit 1
+                  ;;
+                *)
+                  echo "Unknown status"
+                  exit 1
+                esac
+              sleep 10
+            done
 
-# Orchestrate jobs using workflows
-# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
 workflows:
-  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
-    # Inside the workflow, you define the jobs you want to run.
+  weekly-testrigor-run:
+    triggers:
+      - schedule:
+          cron: "30 5 * * 2" # 5:30 AM UTC = 11:00 AM IST on Tuesdays
+          filters:
+            branches:
+              only:
+                - main
     jobs:
-      - say-hello
+      - trigger-testrigor-suite
